### ISSUE TITLE
GettingStarted: Deploying: arkb

### ISSUE THREAD

**Issue by DanMacDonald** [twilson63/permaweb-cookbook#10]
Lots of subtitles to discuss with this one.

- By default deploys each file as it's own transaction to L1
- These can be dropped - but re-running the command after they are dropped will often re-deploy the missing tx/files
- Only re-posts files that are missing / changed

- Can be used to deploy files as a bundle though bundlr network, but requires extra steps to fund a deposit, probably better off using BundlrCLI as you will pay the arkb fee AND the bundlr fee.

- If files are <100KB in size, `node2.bundlr.network` will post them for free (but arkb still takes a fee)

Example command line and expected results...

```arkb deploy ./build --wallet ~/arweave/testWallet/PeZMM2...hE93S0.json```
![arkb summary](https://arweave.net/DtvcbcrjKYRznizrPGHgcUU1IOpn6guS_FpDj2y1gqw/image24.png)
![arkb confirm](https://arweave.net/DtvcbcrjKYRznizrPGHgcUU1IOpn6guS_FpDj2y1gqw/image25.png)

Something like the above (feel free to use your own example)

**Comment by PBillingsby** [comment]
@DanMacDonald Do you think it would be wise to write about uploading data **AND** deploying permaweb apps? Trying to figure out how to "bite-sized" chunk this one

**Comment by PBillingsby** [comment]
@twilson63 would love to know your thoughts on my comment above?

**Comment by DanMacDonald** [comment]
Uploading individual pieces of data is often better done though the browser, either using arweave.app or ardrive.io (and other browser options). If someone needs `arkb` it's probably because they are uploading a directory of files, or more commonly a web app.

**Comment by twilson63** [comment]
Have a summary doc describing the options of deploying and then maybe break out a guide for each scenario:

* arkb [standard] - can take longer to confirm since on chain
`arkb deploy [folder] --wallet wallet.json`

* arkb [with Bundlr] - show how to use custom tags and fund wallet
`arkb deploy [folder] --use-bundler https://node2.bundlr.network --wallet wallet.json --tag-name App-Name --tag-value MyApp`

* bundlerClient - can't deploy with custom tags
`bundlr upload-dir ./uploadDir -h <bundlr-url> -c <currency> -w <wallet/private key>`

* arweave_deploy [not recommended] 🤷

**Comment by twilson63** [comment]
---

Also, I would focus the guide on uploading SPA Apps

**Comment by PBillingsby** [comment]
@twilson63 Cheers. I'll get this finished up by tomorrow with focus on SPA!

**Comment by PBillingsby** [comment]
Handling in #43
